modLoader = "javafml"
loaderVersion = "[48,)"
license = "MIT"

[[mods]]
modId = "world_importer"
version = "${version}"
displayName = "World Importer"
authors = "rolling_cat"
description = '''
Import MCA region files from client to server.
'''

[[dependencies.world_importer]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "architectury"
mandatory = true
versionRange = "[10,)"
ordering = "AFTER"
side = "BOTH"
