modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"

[[mods]]
modId = "world_importer"
version = "${version}"
displayName = "World Importer"
authors = "rolling_cat"
logoFile = "icon.png"
description = '''
Import MCA region files from client to server.
'''

[[dependencies.world_importer]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.19.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "architectury"
mandatory = true
versionRange = "[7,)"
ordering = "AFTER"
side = "BOTH"
