modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"

[[mods]]
modId = "world_importer"
version = "${version}"
displayName = "World Importer"
authors = "rolling_cat"
description = '''
Import MCA region files from client to server.
'''

[[dependencies.world_importer]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "architectury"
mandatory = true
versionRange = "[8,)"
ordering = "AFTER"
side = "BOTH"
