modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "world_importer"
version = "${version}"
displayName = "World Importer"
authors = "rolling_cat"
logoFile = "icon.png"
description = '''
Import MCA region files from client to server.
'''

[[dependencies.world_importer]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.world_importer]]
modId = "architectury"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"
